
export enum PenaltyType {
  MIE_QIAN = 'MIE_QIAN',
  MIE_WAN = 'MIE_WAN',
  MIE_SHU_LIU_SHENG = 'MIE_SHU_LIU_SHENG',
  MIE_PAI_CI_XU = 'MIE_PAI_CI_XU',
  MIE_PAI_LUAN_XU = 'MIE_PAI_LUAN_XU',
  WAN_QIAN_BAI_XIA_MIE_SHI = 'WAN_QIAN_BAI_XIA_MIE_SHI',
  MIE_SHI_FAIL = 'MIE_SHI_FAIL',
  LOU_ZHUANG = 'LOU_ZHUANG',
  ZONG_ZHUANG = 'ZONG_ZHUANG',
  JI_ZHUO = 'JI_ZHUO',
  JI_ZHUO_LIAN_ZHANG = 'JI_ZHUO_LIAN_ZHANG',
  JI_ZHUO_JIAN = 'JI_ZHUO_JIAN',
  JI_ZHUO_PARTNER = 'JI_ZHUO_PARTNER',
  ZHUANG_JI_ZHUO = 'ZHUANG_JI_ZHUO',
  JI_ZHUO_ZHUANG_FA = 'JI_ZHUO_ZHUANG_FA',
  ZHUANG_FA_SHANG_ZHUANG = 'ZHUANG_FA_SHANG_ZHUANG',
  KAI_JIN_MEN = 'KAI_JIN_MEN',
  WRONG_LEAD_PRIORITY = 'WRONG_LEAD_PRIORITY',
  JIE_SE = 'JIE_SE',
  ZHUO_QU = 'ZHUO_QU',
  GUA_LI = 'GUA_LI',
  GUA_WAN = 'GUA_WAN',
  GUAN_SHANG_DOU_SHI = 'GUAN_SHANG_DOU_SHI',
  GAO_BAI_FA_SHI = 'GAO_BAI_FA_SHI',
  GAO_BAI_LATE_PENALTY = 'GAO_BAI_LATE_PENALTY',
  GUAN_ZHEN_DOU_SHI = 'GUAN_ZHEN_DOU_SHI',
  GUAN_ZHEN_R7 = 'GUAN_ZHEN_R7',
  LEAD_QIAN_WAN_EXCEPTION = 'LEAD_QIAN_WAN_EXCEPTION',
  LEAD_QIAN_WAN = 'LEAD_QIAN_WAN',
  ZONG_QU_GAME = 'ZONG_QU', 
  ZONG_SHI = 'ZONG_SHI',
  ZONG_SHI_QING = 'ZONG_SHI_QING',
  FANG_GONG_QIAN = 'FANG_GONG_QIAN',
  QIN_WANG = 'QIN_WANG',
  GUI_BI_FO_CHI_JIAO = 'GUI_BI_FO_CHI_JIAO',
  JI_ZHUO_WAN_BAI = 'JI_ZHUO_WAN_BAI',
  ZONG_ZHUANG_WAN_BAI = 'ZONG_ZHUANG_WAN_BAI',
  LOU_ZHUANG_WAN_BAI = 'LOU_ZHUANG_WAN_BAI',
  JI_ZHUO_RED_ON_RED = 'JI_ZHUO_RED_ON_RED',
  LOU_ZHUANG_MIN = 'LOU_ZHUANG_MIN',
  LOU_ZHUANG_SEQ = 'LOU_ZHUANG_SEQ',
  LOU_ZHUANG_FAIL = 'LOU_ZHUANG_FAIL',
  LOU_ZHUANG_WEAK = 'LOU_ZHUANG_WEAK',
  LOU_ZHUANG_AUTO = 'LOU_ZHUANG_AUTO',
  ZONG_ZHUANG_BAI = 'ZONG_ZHUANG_BAI',
  ZONG_BAI = 'ZONG_BAI',
  MIE_PAI_LUAN_XU_CASH = 'MIE_PAI_LUAN_XU_CASH',
  MIE_PAI_LUAN_XU_ORDER = 'MIE_PAI_LUAN_XU_ORDER',
  
  // New / Updated Rules
  DAO_LI = 'DAO_LI',
  BU_LI_WAN = 'BU_LI_WAN',
  BU_LI_SHANG = 'BU_LI_SHANG',
  DAO_LI_QIAN_HONG = 'DAO_LI_QIAN_HONG',
  TI_JIN_QIAN_WANG = 'TI_JIN_QIAN_WANG',
  WO_DI_BAI_LAO = 'WO_DI_BAI_LAO',
  WU_SHANG_BAO_BAI = 'WU_SHANG_BAO_BAI',
  BU_BAO_BAI = 'BU_BAO_BAI',
  QIAN_SENG_WO_DI = 'QIAN_SENG_WO_DI',
  JIN_MEN_CI_XU = 'JIN_MEN_CI_XU',
  WU_ZHUO_TI_WAN = 'WU_ZHUO_TI_WAN',
  CHUANG_QIAN = 'CHUANG_QIAN'
}

export const RULE_DESCRIPTIONS: Record<string, string> = {
  [PenaltyType.MIE_QIAN]: "灭千：随意丢弃千万。",
  [PenaltyType.MIE_WAN]: "灭万：不小心丢弃万万。",
  [PenaltyType.MIE_SHU_LIU_SHENG]: "灭熟留生：丢弃安全牌而保留危险牌。",
  [PenaltyType.MIE_PAI_CI_XU]: "灭牌次序：违反弃牌优先顺序。",
  [PenaltyType.MIE_PAI_LUAN_XU]: "灭牌乱序：未按严格的弃牌桶顺序丢弃。",
  [PenaltyType.WAN_QIAN_BAI_XIA_MIE_SHI]: "万千百下灭十子：大牌在桌时错误灭十。",
  [PenaltyType.QIN_WANG]: "勤王：0墩+强牌+连张 -> 必须用最小的连张牌捉打。",
  [PenaltyType.GUI_BI_FO_CHI_JIAO]: "规避佛赤脚：0墩持百五 vs 青牌，必须用百五。",
  [PenaltyType.FANG_GONG_QIAN]: "放功千：千万捉了百万，你持万万却未捉千万。",
  [PenaltyType.LOU_ZHUANG]: "漏庄：未能顶住庄家。",
  [PenaltyType.ZONG_ZHUANG]: "纵庄：放任庄家赢牌或未正确捉打。",
  [PenaltyType.ZONG_BAI]: "纵百：十字门已开，百老领先大牌，你有大牌却未捉打。",
  [PenaltyType.JI_ZHUO]: "急捉：捉牌理由不足（非真张/大张/连张）或牌力不够。",
  [PenaltyType.ZONG_QU_GAME]: "纵趣：当趣张（极）称霸牌池时，持有大牌者必须捉打，违者包赔。",
  [PenaltyType.ZONG_SHI]: "纵十：未能捉住赢牌的十字门牌。",
  [PenaltyType.LEAD_QIAN_WAN]: "首发千万：禁手。",
  [PenaltyType.KAI_JIN_MEN]: "开禁门：不必要地首发新花色。",
  [PenaltyType.MIE_PAI_LUAN_XU_CASH]: "灭牌乱序（十）：持有红十时不能打出最后一张青十。",
  [PenaltyType.MIE_PAI_LUAN_XU_ORDER]: "灭牌乱序（次序）：必须按顺序弃牌：青十 > 趣/禁门 > 趣/熟门 > 红牌。",
  [PenaltyType.JI_ZHUO_LIAN_ZHANG]: "急捉：不符合勤王条件（非0墩或无大牌），不可用连张捉打。",
  
  // New Descriptions
  [PenaltyType.DAO_LI]: "倒立：持有万万和千万（无百万），首发千万为严重违例。",
  [PenaltyType.BU_LI_WAN]: "不立万：持有万万和千万（无百万），首发必须立万（出万万），否则违例。",
  [PenaltyType.BU_LI_SHANG]: "不立赏：持有同门赏、肩，首发必须出赏、肩或其同花顺连牌，否则违例。",
  [PenaltyType.DAO_LI_QIAN_HONG]: "倒立千红：持有万万，首发千万，以急桌论处。",
  [PenaltyType.TI_JIN_QIAN_WANG]: "提尽千王：双持万千只能首发红万，千僧留守，违者包赔。",
  [PenaltyType.WO_DI_BAI_LAO]: "卧底百老：庄家已首发过，或两门熟门已定，百老不应再出十字门。",
  [PenaltyType.WU_SHANG_BAO_BAI]: "无赏报百：手中无赏，不应首发十字门报百。",
  [PenaltyType.BU_BAO_BAI]: "不报百：符合报百条件（闲家、持百、有熟门）必须首发十字门。",
  [PenaltyType.QIAN_SENG_WO_DI]: "千僧卧底：无千万万万，有百万及大青张，应先发百万。",
  [PenaltyType.JIN_MEN_CI_XU]: "禁门次序：三门优先级高于十字门。应先发三门。",
  [PenaltyType.WU_ZHUO_TI_WAN]: "五桌提万：剩余4张牌时违规提万。",
  [PenaltyType.CHUANG_QIAN]: "闯千：单持千万（无百万），首发千万属于违规（除非顶色）。"
};
